root = "."
testdata_dir = "testdata"
tmp_dir = "tmp"

[build]
  args_bin = ["--data=tmp/alina_data", "--cors-allow-all=true"]
  bin = "./tmp/main"
  cmd = "go build -o ./tmp/main cmd/alina/main.go"
  delay = 1000
  exclude_dir = ["assets", "tmp", "vendor", "testdata"]
  exclude_file = ["db/query.sql.go", "db/models.go", "db/db.go"]
  exclude_regex = ["_test.go"]
  exclude_unchanged = false
  follow_symlink = false
  full_bin = ""
  include_dir = []
  include_ext = ["go", "tpl", "tmpl", "html", 'sql']
  include_file = []
  kill_delay = 500
  log = "build-errors.log"
  poll = false
  poll_interval = 500
  post_cmd = []
  pre_cmd = ["sqlc generate --file db/sqlc.yaml"]
  rerun = false
  rerun_delay = 500
  send_interrupt = true
  stop_on_error = true

[color]
  app = ""
  build = "yellow"
  main = "magenta"
  runner = "green"
  watcher = "cyan"

[log]
  main_only = false
  silent = false
  time = false

[misc]
  clean_on_exit = false

[screen]
  clear_on_rebuild = false
  keep_scroll = true
