// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"net/netip"

	"github.com/jackc/pgx/v5/pgtype"
)

type File struct {
	ID         int32
	CreatedAt  pgtype.Timestamp
	LastAccess pgtype.Timestamp
	MimeType   string
	FileSize   int64
	IpAddr     netip.Addr
	Hash       string
	Name       string
}
