// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"database/sql"
	"time"
)

type File struct {
	ID         interface{}
	CreatedAt  time.Time
	LastAccess time.Time
	MimeType   sql.NullString
	FileSize   int64
	Name       string
}
