CREATE TABLE IF NOT EXISTS files (
	id SERIAL PRIMARY KEY,
	created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	last_access TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	mime_type VARCHAR(100),
	file_size BIGINT NOT NULL,
	name VARCHAR(255) NOT NULL
);
