BEGIN;

CREATE TABLE IF NOT EXISTS files (
	id SERIAL PRIMARY KEY,
	created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	last_access TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	mime_type VARCHAR(64) NOT NULL,
	file_size BIGINT NOT NULL,
	ip_addr INET NOT NULL,
	hash VARCHAR(64) NOT NULL, /* blake2b-256 */
	name VARCHAR(256) NOT NULL
);

CREATE TABLE IF NOT EXISTS chunked (
	id SERIAL PRIMARY KEY,
	created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	last_access TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	file_size BIGINT NOT NULL,
	ip_addr INET NOT NULL,
	chunks_left INT NOT NULL,
	name VARCHAR(256) NOT NULL
);

COMMIT;
